server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://timeflowdb.cn60c2i6arhm.ap-southeast-2.rds.amazonaws.com:3306/timeflowdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

    username: admin
    password: 20020619
  thymeleaf:
    cache: false
  # spring data jpa 설정
  security:
    user:
      name: user
      password: 1234
  mvc:
    log-request-details: true

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      indent-output: true
  profiles:
    active: secret
jwt:
  secret: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff

logging:
  level:
    org.springframework.web: DEBUG

  # spring mail sender 설정
  mail:
    host: smtp.gmail.com  #메일 서버의 호스트 주소
    port: 587 # 메일 서버의 포트 번호
    username: kimwalwa0619@gmail.com  # 애플리케이션 비밀번호
    password: otuu rhyh dcmi uveb
    properties:
      mail:
        smtp:
          auth: true # SMTP 인증 사용 여부
          starttls:
            enable: true  # STARTTLS 사용 여부
    default-encoding: UTF-8 # 기본 인코딩 설정
    debug: true # 메일 전송 과정의 디버그 정보 출력 여부